### PR TITLE
Resources section

### PR DESCRIPTION
**Pull request by nathanschram**
I messed up the previous pull request - apologies!

Fixed resources section, made sure files are uploaded and file paths work. Added resources links to each page.

See attached image for what it will look like when Case Studies are linked.

screen shot 2016-01-05 at 3 04 19 pm

### CODE REVIEW

**Comment by iamgaru** [comment]
@nathanschram  thanks looks good - but can't see the Case Studies yet? Have you pushed these changes (*synced*) ? 

Also, do we want to change the background to something more education-based? At the moment all I can read is Superdry ... mmmmm beer, but maybe not on site

**Comment by nathanschram** [comment]
Sorry Nick, I wasn't clear - we don't have any case studies yet. I'm planning have three or four finished each month for the next few months. That photo is an illustration of what it will look like when the case studies are displayed on the resources page. The pull request at the moment has no case studies.

Good point on the background! I'll find another image.

**Comment by iamgaru** [comment]
Cool thanks that makes sense.
N

**Comment by nathanschram** [comment]
What did you think of that wallpaper? I thought it was somewhat appropriate :D

Is this OK for a merge?

**Pull request merged**
